import os

from dotenv import load_dotenv

load_dotenv()


AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_RERANK_ENDPOINT = os.getenv("AZURE_RERANK_ENDPOINT")
AZURE_RERANK_API_KEY = os.getenv("AZURE_RERANK_API_KEY")
AZURE_RERANK_DEPLOYMENT = os.getenv("AZURE_RERANK_DEPLOYMENT")
AZURE_CHAT_DEPLOYMENT = os.getenv("AZURE_CHAT_DEPLOYMENT")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_API_KEY = os.getenv("AZURE_SEARCH_API_KEY")


MAX_CONTEXT_TOKENS = int(os.getenv("MAX_CONTEXT_TOKENS", "5000"))

TOP_K = int(os.getenv("TOP_K", "10"))

AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
AZURE_STORAGE_CONTAINER1 = os.getenv("AZURE_STORAGE_CONTAINER1")
AZURE_STORAGE_CONTAINER2 = os.getenv("AZURE_STORAGE_CONTAINER2")
AZURE_STORAGE_CONTAINER3 = os.getenv("AZURE_STORAGE_CONTAINER3")
AZURE_STORAGE_CONTAINER4 = os.getenv("AZURE_STORAGE_CONTAINER4")


CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "400"))
CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP", "80"))

AZURE_SEARCH_INDEX_NAME = os.getenv("AZURE_SEARCH_INDEX_NAME", "hr-policy-index")
